### ISSUE TITLE
why we need recast in this example?

### ISSUE THREAD

**Issue by ronniegong** [kentcdodds/babel-codemod-example#1]
don't understand why we need recast here
as if we set .babelrc like this
```
{
  "plugins": [
    "./plugin.js"
  ]
}
```
run 'npm run codemod' command, the result is the same

**Comment by ronniegong** [comment]
i see
when we use recast, the 'git diff' command has a clear result, while we get a messy result if not,
is this the only difference ?

**Comment by kentcdodds** [comment]
You got it 👌
